### ISSUE TITLE
Dont work key -l 

### ISSUE THREAD

**Issue by jidckii** [leominov/passbox#1]
Dont work key -l 
work only ls & list

emedvedev@142-PC:~$ passbox l
emedvedev@142-PC:~$ passbox ls
1. admin                		 admin               
emedvedev@142-PC:~$ passbox list
1. admin                		 admin               
emedvedev@142-PC:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
emedvedev@142-PC:~$ uname -a
Linux 142-PC 3.19.0-27-generic #29~14.04.1-Ubuntu SMP Sun Aug 16 01:51:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by leominov** [comment]
09555e86bad4b9e04f32332499c0f1222247f5e0
